"""
MCP Server for מציאות מהתמונה (AliExpress Deals) site.

Provides tools for an AI agent to manage images and products
on the site by directly manipulating the data.js file and
image directories.

Run with:
    python -m mcp_server.server

Or configure in your MCP client (e.g. Claude Desktop, VS Code):
    {
        "mcpServers": {
            "aliexpress-deals": {
                "command": "python",
                "args": ["-m", "mcp_server.server"],
                "cwd": "/path/to/landing_pages/aliexpress_deals"
            }
        }
    }
"""

import base64
import json
import os
import re
import shutil
import uuid
from pathlib import Path

from mcp.server.fastmcp import FastMCP

# ── Configuration ──────────────────────────────────────────────────
SITE_DIR = Path(os.environ.get(
    "SITE_DIR",
    Path(__file__).resolve().parent.parent / "site"
))
DATA_JS_PATH = SITE_DIR / "assets" / "js" / "data.js"
IMAGES_DIR = SITE_DIR / "images"

mcp = FastMCP(
    "aliexpress-deals",
    description="Manage images and AliExpress product links for the מציאות מהתמונה site",
)


# ── data.js read/write ─────────────────────────────────────────────
def _read_data() -> dict:
    """Parse SITE_DATA from data.js into a Python dict."""
    if not DATA_JS_PATH.exists():
        return {"categories": []}

    text = DATA_JS_PATH.read_text(encoding="utf-8")
    match = re.search(r"const\s+SITE_DATA\s*=\s*(\{.*\})\s*;?\s*$", text, re.DOTALL)
    if not match:
        raise ValueError("Could not parse data.js – unexpected format")

    json_str = match.group(1)
    json_str = re.sub(r"//.*", "", json_str)
    json_str = re.sub(r"/\*.*?\*/", "", json_str, flags=re.DOTALL)
    json_str = re.sub(r'(?<=[{,\n])\s*(\w+)\s*:', r' "\1":', json_str)
    json_str = re.sub(r",\s*([}\]])", r"\1", json_str)

    return json.loads(json_str)


def _write_data(data: dict) -> None:
    """Write data dict back to data.js."""
    header = (
        "/**\n"
        " * ====================================\n"
        " * IMAGE DATA – מציאות מהתמונה\n"
        " * ====================================\n"
        " * Auto-generated by MCP server.\n"
        " */\n\n"
    )
    json_str = json.dumps(data, ensure_ascii=False, indent=4)
    DATA_JS_PATH.write_text(header + f"const SITE_DATA = {json_str};\n", encoding="utf-8")


def _find_category(data: dict, category_id: str):
    for cat in data["categories"]:
        if cat["id"] == category_id:
            return cat
    return None


def _find_image(category: dict, image_file: str):
    for img in category.get("images", []):
        if img["file"] == image_file:
            return img
    return None


# ── MCP Tools ──────────────────────────────────────────────────────

@mcp.tool()
def list_categories() -> str:
    """
    List all categories on the site with their image counts.
    Returns a JSON array of categories.
    """
    data = _read_data()
    result = []
    for cat in data["categories"]:
        result.append({
            "id": cat["id"],
            "label": cat["label"],
            "icon": cat["icon"],
            "image_count": len(cat.get("images", [])),
        })
    return json.dumps(result, ensure_ascii=False, indent=2)


@mcp.tool()
def create_category(category_id: str, label: str, icon: str = "📁") -> str:
    """
    Create a new category for organizing images.

    Args:
        category_id: Unique ID (used as folder name, e.g. "pets", "sports"). ASCII only.
        label: Hebrew display name (e.g. "חיות מחמד")
        icon: Emoji icon for the tab (e.g. "🐾")
    """
    data = _read_data()
    if _find_category(data, category_id):
        return json.dumps({"error": f"Category '{category_id}' already exists"})

    data["categories"].append({
        "id": category_id,
        "label": label,
        "icon": icon,
        "images": [],
    })
    cat_dir = IMAGES_DIR / category_id
    cat_dir.mkdir(parents=True, exist_ok=True)
    _write_data(data)
    return json.dumps({"status": "created", "category_id": category_id, "label": label})


@mcp.tool()
def delete_category(category_id: str) -> str:
    """
    Delete a category and all its images.

    Args:
        category_id: The category ID to delete.
    """
    data = _read_data()
    cat = _find_category(data, category_id)
    if not cat:
        return json.dumps({"error": f"Category '{category_id}' not found"})

    data["categories"] = [c for c in data["categories"] if c["id"] != category_id]
    cat_dir = IMAGES_DIR / category_id
    if cat_dir.exists():
        shutil.rmtree(cat_dir)
    _write_data(data)
    return json.dumps({"status": "deleted", "category_id": category_id})


@mcp.tool()
def list_images(category_id: str) -> str:
    """
    List all image entries in a category.

    Args:
        category_id: The category to list images from.
    """
    data = _read_data()
    cat = _find_category(data, category_id)
    if not cat:
        return json.dumps({"error": f"Category '{category_id}' not found"})
    return json.dumps(cat.get("images", []), ensure_ascii=False, indent=2)


@mcp.tool()
def upload_image(
    category_id: str,
    title: str,
    description: str,
    image_data_base64: str,
    filename: str = "image.jpg",
) -> str:
    """
    Upload an image (as base64) to a category and create a data entry for it.
    Products can be added afterward with add_product.

    Args:
        category_id: Target category ID (e.g. "parenting", "kitchen").
        title: Hebrew title for the image entry.
        description: Hebrew description of the image.
        image_data_base64: The image file content encoded as base64 string.
        filename: Desired filename (e.g. "my-photo.jpg"). Will be sanitized.
    """
    data = _read_data()
    cat = _find_category(data, category_id)
    if not cat:
        return json.dumps({"error": f"Category '{category_id}' not found"})

    # Decode image
    try:
        image_bytes = base64.b64decode(image_data_base64)
    except Exception as e:
        return json.dumps({"error": f"Invalid base64 data: {e}"})

    # Sanitize filename
    ext = Path(filename).suffix.lower() or ".jpg"
    allowed = {".jpg", ".jpeg", ".png", ".webp", ".avif", ".gif", ".svg"}
    if ext not in allowed:
        return json.dumps({"error": f"Unsupported file type: {ext}. Allowed: {allowed}"})

    safe_name = re.sub(r"[^\w\-.]", "_", Path(filename).stem) or str(uuid.uuid4())[:8]
    final_name = f"{safe_name}{ext}"

    cat_dir = IMAGES_DIR / category_id
    cat_dir.mkdir(parents=True, exist_ok=True)

    dest = cat_dir / final_name
    counter = 1
    while dest.exists():
        final_name = f"{safe_name}_{counter}{ext}"
        dest = cat_dir / final_name
        counter += 1

    dest.write_bytes(image_bytes)

    image_entry = {
        "file": final_name,
        "title": title,
        "description": description,
        "products": [],
    }
    cat["images"].append(image_entry)
    _write_data(data)

    return json.dumps({
        "status": "uploaded",
        "path": f"images/{category_id}/{final_name}",
        "image_entry": image_entry,
    }, ensure_ascii=False)


@mcp.tool()
def add_image_entry(
    category_id: str,
    file: str,
    title: str,
    description: str,
) -> str:
    """
    Add a data entry for an image file that already exists in the images directory.
    Use this when the image file was placed manually (e.g. via git).

    Args:
        category_id: Target category ID.
        file: Image filename (must exist in images/<category_id>/).
        title: Hebrew title for the image.
        description: Hebrew description.
    """
    data = _read_data()
    cat = _find_category(data, category_id)
    if not cat:
        return json.dumps({"error": f"Category '{category_id}' not found"})

    if _find_image(cat, file):
        return json.dumps({"error": f"Image entry '{file}' already exists in '{category_id}'"})

    image_path = IMAGES_DIR / category_id / file
    file_exists = image_path.exists()

    entry = {
        "file": file,
        "title": title,
        "description": description,
        "products": [],
    }
    cat["images"].append(entry)
    _write_data(data)

    return json.dumps({
        "status": "added",
        "file_exists_on_disk": file_exists,
        "image_entry": entry,
    }, ensure_ascii=False)


@mcp.tool()
def delete_image(category_id: str, image_file: str, delete_file: bool = True) -> str:
    """
    Delete an image entry and optionally the image file from disk.

    Args:
        category_id: The category containing the image.
        image_file: The image filename to delete.
        delete_file: Whether to also delete the image file from disk (default True).
    """
    data = _read_data()
    cat = _find_category(data, category_id)
    if not cat:
        return json.dumps({"error": f"Category '{category_id}' not found"})

    img = _find_image(cat, image_file)
    if not img:
        return json.dumps({"error": f"Image '{image_file}' not found in '{category_id}'"})

    cat["images"] = [i for i in cat["images"] if i["file"] != image_file]

    deleted_from_disk = False
    if delete_file:
        fp = IMAGES_DIR / category_id / image_file
        if fp.exists():
            fp.unlink()
            deleted_from_disk = True

    _write_data(data)
    return json.dumps({"status": "deleted", "image_file": image_file, "deleted_from_disk": deleted_from_disk})


@mcp.tool()
def add_product(
    category_id: str,
    image_file: str,
    name: str,
    price: str,
    url: str,
    icon: str = "🛒",
) -> str:
    """
    Add an AliExpress product link to an image entry.

    Args:
        category_id: The category containing the image.
        image_file: The image filename to add the product to.
        name: Hebrew product name (e.g. "מנורת לילה LED").
        price: Price range string (e.g. "₪15–30").
        url: Full AliExpress product URL (affiliate link).
        icon: Emoji icon for the product (e.g. "💡").
    """
    data = _read_data()
    cat = _find_category(data, category_id)
    if not cat:
        return json.dumps({"error": f"Category '{category_id}' not found"})

    img = _find_image(cat, image_file)
    if not img:
        return json.dumps({"error": f"Image '{image_file}' not found in '{category_id}'"})

    product = {"name": name, "price": price, "url": url, "icon": icon}
    img["products"].append(product)
    _write_data(data)

    return json.dumps({
        "status": "added",
        "product": product,
        "total_products": len(img["products"]),
    }, ensure_ascii=False)


@mcp.tool()
def remove_product(category_id: str, image_file: str, product_index: int) -> str:
    """
    Remove a product from an image by its index (0-based).

    Args:
        category_id: The category containing the image.
        image_file: The image filename.
        product_index: Zero-based index of the product to remove.
    """
    data = _read_data()
    cat = _find_category(data, category_id)
    if not cat:
        return json.dumps({"error": f"Category '{category_id}' not found"})

    img = _find_image(cat, image_file)
    if not img:
        return json.dumps({"error": f"Image '{image_file}' not found"})

    products = img.get("products", [])
    if product_index < 0 or product_index >= len(products):
        return json.dumps({"error": f"Index {product_index} out of range (0–{len(products) - 1})"})

    removed = products.pop(product_index)
    _write_data(data)
    return json.dumps({"status": "removed", "product": removed}, ensure_ascii=False)


@mcp.tool()
def get_site_data() -> str:
    """
    Get the full site data (all categories, images, and products).
    Useful for understanding current state before making changes.
    """
    data = _read_data()
    return json.dumps(data, ensure_ascii=False, indent=2)


# ── Run ────────────────────────────────────────────────────────────
if __name__ == "__main__":
    mcp.run()
