"""
FastAPI Management API for מציאות מהתמונה (AliExpress Deals) site.

Provides REST endpoints to:
- List categories and images
- Upload images to category directories
- Add/update/delete image entries with product links
- Add/remove categories

The API reads and writes site/assets/js/data.js and site/images/ directly.
"""

import json
import os
import re
import shutil
import uuid
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# ── Paths ──────────────────────────────────────────────────────────
BASE_DIR = Path(os.environ.get("SITE_DIR", "/app/site"))
DATA_JS_PATH = BASE_DIR / "assets" / "js" / "data.js"
IMAGES_DIR = BASE_DIR / "images"

app = FastAPI(
    title="AliExpress Deals – Management API",
    version="1.0.0",
    description="API for managing images and products on the מציאות מהתמונה site",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Pydantic models ───────────────────────────────────────────────
class Coords(BaseModel):
    x: float
    y: float


class Product(BaseModel):
    name: str
    price: str
    url: str
    icon: str = "🛒"
    coords: Optional[Coords] = None


class ImageEntry(BaseModel):
    file: str
    title: str
    description: str
    products: list[Product] = []


class CategoryCreate(BaseModel):
    id: str
    label: str
    icon: str = "📁"


class UpdateImageEntry(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None


class UpdateProduct(BaseModel):
    name: Optional[str] = None
    price: Optional[str] = None
    url: Optional[str] = None
    icon: Optional[str] = None
    coords: Optional[Coords] = None


# ── data.js read/write helpers ────────────────────────────────────
def read_data() -> dict:
    """Parse SITE_DATA from data.js → Python dict."""
    if not DATA_JS_PATH.exists():
        return {"categories": []}

    text = DATA_JS_PATH.read_text(encoding="utf-8")

    # Extract JSON object from: const SITE_DATA = { ... };
    match = re.search(r"const\s+SITE_DATA\s*=\s*(\{.*\})\s*;?\s*$", text, re.DOTALL)
    if not match:
        raise HTTPException(500, "Could not parse data.js – unexpected format")

    json_str = match.group(1)

    # JS → JSON: add quotes to unquoted keys, handle trailing commas
    # Replace single-line comments
    json_str = re.sub(r"//.*", "", json_str)
    # Replace multi-line comments
    json_str = re.sub(r"/\*.*?\*/", "", json_str, flags=re.DOTALL)
    # Quote unquoted keys: word: → "word":
    json_str = re.sub(r'(?<=[{,\n])\s*(\w+)\s*:', r' "\1":', json_str)
    # Remove trailing commas before } or ]
    json_str = re.sub(r",\s*([}\]])", r"\1", json_str)

    try:
        return json.loads(json_str)
    except json.JSONDecodeError as e:
        raise HTTPException(500, f"Failed to parse data.js as JSON: {e}")


def write_data(data: dict) -> None:
    """Write data dict back to data.js in a readable JS format."""
    header = '''\
/**
 * ====================================
 * IMAGE DATA – מציאות מהתמונה
 * ====================================
 * Auto-generated by the management API.
 * Manual edits are fine – the API preserves the JS format.
 */

'''
    json_str = json.dumps(data, ensure_ascii=False, indent=4)
    js_content = header + f"const SITE_DATA = {json_str};\n"
    DATA_JS_PATH.write_text(js_content, encoding="utf-8")


# ── Helpers ────────────────────────────────────────────────────────
def find_category(data: dict, category_id: str) -> dict | None:
    for cat in data["categories"]:
        if cat["id"] == category_id:
            return cat
    return None


def find_image(category: dict, image_file: str) -> dict | None:
    for img in category["images"]:
        if img["file"] == image_file:
            return img
    return None


def ensure_category_dir(category_id: str) -> Path:
    d = IMAGES_DIR / category_id
    d.mkdir(parents=True, exist_ok=True)
    return d


# ── API Endpoints ──────────────────────────────────────────────────

# ── Categories ─────────────────────────────────────────────────────
@app.get("/api/categories")
def list_categories():
    """List all categories with image count."""
    data = read_data()
    return [
        {
            "id": cat["id"],
            "label": cat["label"],
            "icon": cat["icon"],
            "image_count": len(cat.get("images", [])),
        }
        for cat in data["categories"]
    ]


@app.post("/api/categories")
def create_category(req: CategoryCreate):
    """Create a new category."""
    data = read_data()
    if find_category(data, req.id):
        raise HTTPException(409, f"Category '{req.id}' already exists")

    data["categories"].append(
        {"id": req.id, "label": req.label, "icon": req.icon, "images": []}
    )
    ensure_category_dir(req.id)
    write_data(data)
    return {"status": "created", "category": req.id}


@app.delete("/api/categories/{category_id}")
def delete_category(category_id: str):
    """Delete a category and its images."""
    data = read_data()
    cat = find_category(data, category_id)
    if not cat:
        raise HTTPException(404, f"Category '{category_id}' not found")

    data["categories"] = [c for c in data["categories"] if c["id"] != category_id]

    cat_dir = IMAGES_DIR / category_id
    if cat_dir.exists():
        shutil.rmtree(cat_dir)

    write_data(data)
    return {"status": "deleted", "category": category_id}


# ── Images ─────────────────────────────────────────────────────────
@app.get("/api/categories/{category_id}/images")
def list_images(category_id: str):
    """List all image entries in a category."""
    data = read_data()
    cat = find_category(data, category_id)
    if not cat:
        raise HTTPException(404, f"Category '{category_id}' not found")
    return cat.get("images", [])


@app.post("/api/categories/{category_id}/images/upload")
async def upload_image(
    category_id: str,
    title: str,
    description: str = "",
    file: UploadFile = File(...),
):
    """
    Upload an image file to a category directory and create an image entry.
    Returns the created image entry (without products yet — add those separately).
    """
    data = read_data()
    cat = find_category(data, category_id)
    if not cat:
        raise HTTPException(404, f"Category '{category_id}' not found")

    # Sanitize filename
    ext = Path(file.filename).suffix.lower() if file.filename else ".jpg"
    if ext not in {".jpg", ".jpeg", ".png", ".webp", ".avif", ".gif", ".svg"}:
        raise HTTPException(400, f"Unsupported file type: {ext}")

    safe_name = re.sub(r"[^\w\-.]", "_", Path(file.filename).stem) if file.filename else str(uuid.uuid4())[:8]
    filename = f"{safe_name}{ext}"

    # Avoid collisions
    cat_dir = ensure_category_dir(category_id)
    dest = cat_dir / filename
    counter = 1
    while dest.exists():
        filename = f"{safe_name}_{counter}{ext}"
        dest = cat_dir / filename
        counter += 1

    # Save file
    content = await file.read()
    dest.write_bytes(content)

    # Add entry to data
    image_entry = {
        "file": filename,
        "title": title,
        "description": description,
        "products": [],
    }
    cat["images"].append(image_entry)
    write_data(data)

    return {"status": "uploaded", "image": image_entry, "path": f"images/{category_id}/{filename}"}


@app.post("/api/categories/{category_id}/images/entry")
def add_image_entry(category_id: str, req: ImageEntry):
    """
    Add an image entry (for an already-existing image file) with products.
    Use this when the image is already in the images/ directory.
    """
    data = read_data()
    cat = find_category(data, category_id)
    if not cat:
        raise HTTPException(404, f"Category '{category_id}' not found")

    if find_image(cat, req.file):
        raise HTTPException(409, f"Image entry '{req.file}' already exists in '{category_id}'")

    cat["images"].append(req.model_dump())
    write_data(data)
    return {"status": "added", "image": req.model_dump()}


@app.delete("/api/categories/{category_id}/images/{image_file}")
def delete_image(category_id: str, image_file: str, delete_file: bool = True):
    """Delete an image entry and optionally the image file."""
    data = read_data()
    cat = find_category(data, category_id)
    if not cat:
        raise HTTPException(404, f"Category '{category_id}' not found")

    img = find_image(cat, image_file)
    if not img:
        raise HTTPException(404, f"Image '{image_file}' not found in '{category_id}'")

    cat["images"] = [i for i in cat["images"] if i["file"] != image_file]

    if delete_file:
        file_path = IMAGES_DIR / category_id / image_file
        if file_path.exists():
            file_path.unlink()

    write_data(data)
    return {"status": "deleted", "image": image_file}


# ── Update image entry ─────────────────────────────────────────────
@app.put("/api/categories/{category_id}/images/{image_file}")
def update_image(category_id: str, image_file: str, req: UpdateImageEntry):
    """Update an image entry's title or description."""
    data = read_data()
    cat = find_category(data, category_id)
    if not cat:
        raise HTTPException(404, f"Category '{category_id}' not found")
    img = find_image(cat, image_file)
    if not img:
        raise HTTPException(404, f"Image '{image_file}' not found in '{category_id}'")

    if req.title is not None:
        img["title"] = req.title
    if req.description is not None:
        img["description"] = req.description
    write_data(data)
    return {"status": "updated", "image": img}


# ── Products ───────────────────────────────────────────────────────
@app.get("/api/categories/{category_id}/images/{image_file}/products")
def list_products(category_id: str, image_file: str):
    """List all products for a specific image."""
    data = read_data()
    cat = find_category(data, category_id)
    if not cat:
        raise HTTPException(404, f"Category '{category_id}' not found")
    img = find_image(cat, image_file)
    if not img:
        raise HTTPException(404, f"Image '{image_file}' not found")
    return img.get("products", [])


@app.post("/api/categories/{category_id}/images/{image_file}/products")
def add_product(category_id: str, image_file: str, product: Product):
    """Add a product link to an image."""
    data = read_data()
    cat = find_category(data, category_id)
    if not cat:
        raise HTTPException(404, f"Category '{category_id}' not found")
    img = find_image(cat, image_file)
    if not img:
        raise HTTPException(404, f"Image '{image_file}' not found")

    img["products"].append(product.model_dump())
    write_data(data)
    return {"status": "added", "product": product.model_dump(), "total_products": len(img["products"])}


@app.put("/api/categories/{category_id}/images/{image_file}/products/{product_index}")
def update_product(category_id: str, image_file: str, product_index: int, req: UpdateProduct):
    """Update a product by index."""
    data = read_data()
    cat = find_category(data, category_id)
    if not cat:
        raise HTTPException(404, f"Category '{category_id}' not found")
    img = find_image(cat, image_file)
    if not img:
        raise HTTPException(404, f"Image '{image_file}' not found")

    products = img.get("products", [])
    if product_index < 0 or product_index >= len(products):
        raise HTTPException(404, f"Product index {product_index} out of range (0–{len(products) - 1})")

    product = products[product_index]
    if req.name is not None:
        product["name"] = req.name
    if req.price is not None:
        product["price"] = req.price
    if req.url is not None:
        product["url"] = req.url
    if req.icon is not None:
        product["icon"] = req.icon
    if req.coords is not None:
        product["coords"] = req.coords.model_dump()

    write_data(data)
    return {"status": "updated", "product": product}


@app.delete("/api/categories/{category_id}/images/{image_file}/products/{product_index}")
def delete_product(category_id: str, image_file: str, product_index: int):
    """Delete a product by index from an image."""
    data = read_data()
    cat = find_category(data, category_id)
    if not cat:
        raise HTTPException(404, f"Category '{category_id}' not found")
    img = find_image(cat, image_file)
    if not img:
        raise HTTPException(404, f"Image '{image_file}' not found")

    products = img.get("products", [])
    if product_index < 0 or product_index >= len(products):
        raise HTTPException(404, f"Product index {product_index} out of range (0–{len(products) - 1})")

    removed = products.pop(product_index)
    write_data(data)
    return {"status": "deleted", "removed_product": removed}


# ── Bulk / convenience ─────────────────────────────────────────────
@app.get("/api/data")
def get_full_data():
    """Get the full SITE_DATA object."""
    return read_data()


@app.get("/api/health")
def health():
    return {"status": "ok", "data_js_exists": DATA_JS_PATH.exists()}
